repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.3
    hooks:
      - id: commitizen
        name: Lint commit message
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: Dart format
        name: Dart Formatter
        entry: dart format . --set-exit-if-changed
        language: system
        types: [dart]
        pass_filenames: false
      - id: Flutter analyze
        name: Flutter analyzer
        entry: flutter analyze .
        language: system
        pass_filenames: false
