repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen
        name: Lint commit message
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: dart-version
        name: Dart version
        entry: dart --version
        language: system
        pass_filenames: false
      - id: dart-format
        name: Dart Formatter
        entry: dart format . --set-exit-if-changed
        language: system
        types: [dart]
        pass_filenames: false
      - id: flutter-analyze
        name: Flutter analyzer
        entry: flutter analyze .
        language: system
        pass_filenames: false
