name: Build APK

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Busybe release'
        required: true
        default: '1.1.0'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag_name }}
          release_name: 'Busybe APK'
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/app-release.apk
