name: iOS Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v5

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 13'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter drive \
          --driver=test_driver/integration_test.dart \
          --target=integration_test/count_test.dart
