name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
      - name: Ensure Git uses UTF-8
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global i18n.commitEncoding UTF-8
          git config --global i18n.logOutputEncoding UTF-8
      - uses: actions/checkout@v4
      - run: file -i lib/app.dart
      - uses: actions/setup-python@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
      - uses: pre-commit/action@v3.0.1
