name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: file -i lib/app.dart
      - uses: actions/setup-python@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
      - run: git ls-files --eol lib/*
      - run: set -x; dart format --output=show .
      - uses: pre-commit/action@v3.0.1
