name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2

      # - run: make unit-tests

  ios-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 15"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - name: Run integration tests
        run: |
          make start-wiremock &
          make integration-tests

    android-test:
      runs-on: ubuntu-latest
      needs: common

      steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2
          with:
            channel: "stable"

        - name: Enable KVM
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

        - run: flutter pub get

        - name: Run integration tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: |
              make start-wiremock &
              make integration-tests
