name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2

      # - run: make unit-tests

  ios-test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - name: Run integration tests
        run: |
          make start-wiremock
          make integration-tests
