name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2

      # - run: make unit-tests

  ios-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 15"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - run: make start-wiremock &

      - name: Run integration tests
        timeout-minutes: 15
        run: |
          make integration-tests

  android-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Clean and Reinstall Android SDK
        run: |
          rm -rf /usr/local/lib/android/sdk/platforms/android-35
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-34"

      - name: Force compileSdkVersion to 34
        run: |
          sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 34/g' android/app/build.gradle
          sed -i 's/targetSdkVersion [0-9]*/targetSdkVersion 34/g' android/app/build.gradle

      - run: flutter pub get

      - run: make start-wiremock &

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 15
        env:
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60
        with:
          api-level: 29
          script: |
            make integration-tests WIREMOCK_URL=http://10.0.2.2:8080