name: Web Deploy

on:
  pull_request:
  push:
    branchs: [main, elis/web-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web

      - name: Checkout Web App
        uses: actions/checkout@v4
        with:
          repository: busybeapp/busybe-web-app
          token: ${{ secrets.CLEARSLATE_PAT }}
          path: webapp

      - name: Push Web App
        run: |
          cd webapp
          rm -Rf *
          cp -r ../build/web/* .
          git add .
          git push origin main
